[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express", "mongoose", "@neondatabase/serverless", "drizzle-orm"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200